name: Android

on:
  pull_request:
    branches:
      - cpp17
  push:
    branches:
      - cpp17

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Prepare
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
          unzip -q -o ./android-ndk-r21-linux-x86_64.zip
      - name: Tests
        run: |
          xmake f -a arm64 -p android --ndk=`pwd`/android-ndk-r21
          xmake -a