name: Fedora

on:
  pull_request:
    branches:
      - cpp17
  push:
    branches:
      - cpp17

jobs:
  build:

    container: fedora:latest
    runs-on: ubuntu-latest

    steps:
      - name: Prepare build tools
        run: |
          uname -a
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make gcc-c++
          dnf -y install perl
          dnf -y upgrade git
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Tests
        env:
          XMAKE_ROOT: y
        run: |
          xmake -a
          xmake -b unitest
          xmake r unitest -co_sched_num 4