name: Windows

on:
  pull_request:
    branches:
      - cpp17
  push:
    branches:
      - cpp17

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Tests
        run: |
          xmake f -a ${{ matrix.arch }}
          xmake -a
          xmake -b unitest
          xmake r unitest -co_sched_num 4